def configure_and_install(rel, distro="python-django", pip="Django"):

    def _import_key(id):
        cmd = "apt-key adv --keyserver keyserver.ubuntu.com " \
              "--recv-keys %s" % id
        try:
            subprocess.check_call(cmd.split(' '))
        except:
            log("Error importing repo key %s" % id, ERROR)

    if rel == 'distro':
        return apt_install(distro, options=['--force-yes'])
    elif rel[:4] == "ppa:":
        src = rel
        subprocess.check_call(["add-apt-repository", "-y", src])

        return apt_install(distro, options=['--force-yes'])

        with open('/etc/apt/sources.list.d/juju_%s_deb.list' % distro.replace('-', '_'), 'w') as f:
            f.write(src)

        return apt_install(distro, options=['--force-yes'])
    elif rel == '':
        return
    else:
        return pip_install(rel)

