- name: get mercurial source
  tags:
    - install
    - upgrade-charm
  hg: repo={{ repos_url }} dest={{ vcs_clone_dir }}
  when: vcs == 'hg' or vcs == 'mercurial' and not repos_branch

- name: get bzr source
  tags:
    - install
    - upgrade-charm
  bzr: name={{ repos_url }} dest={{ vcs_clone_dir }}
  when: vcs == 'bzr' and not repos_branch

- name: get git source
  tags:
    - install
    - upgrade-charm
  git: repo={{ repos_url }} dest={{ vcs_clone_dir }}
  when: vcs == 'git' and not repos_branch

- name: get subversion source
  tags:
    - install
    - upgrade-charm
  subversion: repo={{ repos_url }} dest={{ vcs_clone_dir }} username={{ repos_username }} password={{ repos_password }}
  when: vcs == 'svn' or vcs == 'subversion' and not repos_branch

#VCS + Branch
- name: get mercurial source with branch
  tags:
    - install
    - upgrade-charm
  hg: repo={{ repos_url }} dest={{ vcs_clone_dir }} revision={{ repos_branch }}
  when: vcs == 'hg' or vcs == 'mercurial' and repos_branch

- name: get bzr source
  tags:
    - install
    - upgrade-charm
  bzr: name={{ repos_url }} dest={{ vcs_clone_dir }} version={{ repos_branch }}
  when: vcs == 'bzr' and repos_branch

- name: get git source with branch
  tags:
    - install
    - upgrade-charm
  git: repo={{ repos_url }} dest={{ vcs_clone_dir }} version={{ repos_branch }}
  when: vcs == 'git' and repos_branch

- name: get subversion source
  tags:
    - install
    - upgrade-charm
  subversion: repo={{ repos_url }} dest={{ vcs_clone_dir }} username={{ repos_username }} password={{ repos_password }} revision={{ repos_branch }}
  when: vcs == 'svn' or vcs == 'subversion' and repos_branch
